services:
  # ----------------------------------------------------
  # 1. Laravel API Backend
  # ----------------------------------------------------
  - type: web
    name: pharmacy-api
    runtime: docker
    dockerContext: ./pharmacy-api-production
    dockerfilePath: ./pharmacy-api-production/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:nSaztRVeyWnd1yzgvNnIrgfEqNoTlYgwnKlUfrtj40E=
      - key: JWT_SECRET
        value: 3PphbUNHPnsowpwcxFj6o+wukZ4mkIbfVrue92bdzsQ=
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false
      - key: DB_DATABASE
        value: pharmacy_api_v2
      - key: GEMINI_API_KEY
        sync: false

  # ----------------------------------------------------
  # 2. Pharmacy AI Service (Python FastAPI / Flask Backend)
  # ----------------------------------------------------
  - type: web
    name: pharmacy-ai
    runtime: docker
    dockerContext: ./pharmacy-ai
    dockerfilePath: ./pharmacy-ai/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        value: pharmacy_api_v2
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile

  # ----------------------------------------------------
  # 3. Pharmacy Admin Frontend (React / Vite + Nginx)
  # ----------------------------------------------------
  - type: web
    name: pharmacy-admin
    runtime: docker
    dockerContext: ./pharmacy-admin
    dockerfilePath: ./pharmacy-admin/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: VITE_BACKEND_API_URL
        value: https://pharmacy-api-6hal.onrender.com/api
      - key: VITE_LLM_API_URL
        value: /ai-api

  # ----------------------------------------------------
  # 4. Pharmacy Store Frontend (React / Vite + Nginx)
  # ----------------------------------------------------
  - type: web
    name: pharmacy-store
    runtime: docker
    dockerContext: ./pharmacy-store
    dockerfilePath: ./pharmacy-store/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: VITE_BACKEND_API_URL
        value: https://pharmacy-api-6hal.onrender.com/api
      - key: VITE_LLM_API_URL
        value: /ai-api
